[hekad]
maxprocs = 4
base_dir = "."
max_timer_inject = 100
max_process_duration = 500000

[ProtobufDecoder]
pool_size = 1
encoding_name = "PROTOCOL_BUFFER"

[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
	[TCP:5565.signer.telemetry_0]
	hmac_key = "TODO change on deploy" # TODO update on deploy

[TelemetrySandboxManager]
type = "SandboxManagerFilter"
message_signer = "telemetry"
message_matcher = "Type == 'heka.control.sandbox'"
working_directory = "sandbox"
max_filters = 100

[TelemetryServerInput]
type = "LogfileInput"
logfile = "/var/log/telemetry/telemetry-server.log"
decoder = "TelemetryServerDecoder"
seek_journal_name = "telemetry-server.journal"
use_seek_journal = true 

[TelemetryServerDecoder]
type = "PayloadJsonDecoder"
pool_size = 1
timestamp_layout = "2006-01-02T15:04:05.999Z"

#{"url":"/submit/telemetry/60dfb8c5-9966-4fd8-9b82-3a5ec2ac3d6a/saved-session/Firefox/23.0.1/release/20130814063812","duration_ms":0.547324,"code":200,"size":4819,"level":"info","message":"OK","timestamp":"2013-09-10T20:43:17.217Z"}

[TelemetryServerDecoder.json_map]
Timestamp = "$.timestamp"
Severity = "$.level"
url = "$.url"
duration = "$.duration_ms"
code = "$.code"
size = "$.size"
message = "$.message"

[TelemetryServerDecoder.severity_map]
debug = 1
warning = 2
info = 3

[TelemetryServerDecoder.message_fields]
Type = "TelemetryServerLog"
Payload = ""
url = "%url%"
duration|ms = "%duration%"
code = "%code%"
size|B = "%size%"
message = "%message%"

[TelemetryFilter]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry.lua"
preserve_data = true
memory_limit = 1000000 
instruction_limit = 1000
output_limit = 64000

[TelemetryChannel]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry_channel.lua"
preserve_data = true
memory_limit = 8000000 
instruction_limit = 1000
output_limit = 64000

[TelemetryChannel.config]
rows = 1440
sec_per_row = 60

[TelemetryChannel60Days]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry_channel.lua"
preserve_data = true
memory_limit = 8000000
instruction_limit = 1000
output_limit = 64000

[TelemetryChannel60Days.config]
rows = 1440
sec_per_row = 3600

[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 10
working_directory = "dashboard"

[AMQPOutput]
url = "amqp://guest:guest@10.250.68.186"
exchange = "testout"
exchangeType = "fanout"
message_matcher =  "Type == 'heka.sandbox-output' && Fields[payload_type] == 'cbufd'"
